---
- name: load secrets from ansible vault
  ansible.builtin.include_vars:
    file: "./vars/secrets.yml"

- name: preflight
  ansible.builtin.import_tasks: preflight.yml

- name: build iso
  ansible.builtin.import_tasks: create_iso.yml
