---
galaxy_info:
  role_name: "publish_image"
  standalone: false
  company: ""
  description: >
    Publish image 
  author: rprakashg
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.12"
  platforms:
  galaxy_tags:
    - edge
    - rhel
    - os
    - ostree
    - immutable
dependencies: []
