---
- name: Configure okta auth
  hosts: "localhost"
  become: true    
  tasks:
    - name: include ansible vault secrets with rhuser and rhpassword
      include_vars:
        file: "./vars/secrets.yml"
    - name: configure auth
      ansible.builtin.include_role:
        name: rprakashg.demos.configure_openshift_auth
      vars:
        idp:
          type: OpenID
          name: okta
          claims:
            email:
            - email
            name:
            - name
            preferredUsername:
            - preferred_username
            groups:
            - groups
          extraScopes:
          - email
          - profile
          - groups
          issuer: https://dev-6782679.okta.com
        
        cluster_admin_claim: "cluster-admins"
        delete_default_kubeadmin_user: true