- name: provision required infrastructure for building/managing ostree repo content
  block:
  - name: generate the tfvars file
    template:
      src: ../templates/params.tfvars.j2
      dest: "{{ ansible_tmp }}/ostree-infra-params.tfvars"

  - name: terraform init
    ansible.builtin.shell:
      command: terraform init
      chdir: "{{ terraform_dir }}"
  
  - name: terraform plan
    ansible.builtin.shell:
      command: terraform plan --var-file="{{ {{ ansible_tmp }}/ostree-infra-params.tfvars }}"
      chdir: "{{ terraform_dir }}"

  - name: terraform apply
    ansible.builtin.shell:
      command: terraform apply --var-file="{{ ansible_tmp }}/ostree-infra-params.tfvars"
      chdir: "{{ terraform_dir }}"
  