---
### Defaults
blueprint_name: ""
microshift: false
iso_bucket_name: "rhde-isos"
base_domain: "sandbox2873.opentlc.com"
subdomain: "ostree"

retries: 100
delay: 60

builder_blueprint_name: rfe_installer_blueprint
builder_blueprint_desc: "RHEL For Edge Installer Blueprint"
builder_blueprint_distro: ""
builder_compose_customizations:
  user:
    name: "{{ admin_user }}"
    password: "{{ admin_password }}"
    groups:
    - wheel
builder_kickstart_options:
- lang en_US.UTF-8
- keyboard us
- timezone America/Los_Angeles --utc
- zerombr
- clearpart --all --initlabel
- # Create physical volumes
- part pv.01 --fstype=lvmpv --ondisk=sda --grow --size=20988
- part pv.02 --fstype=lvmpv --ondisk=sdb --grow --size=20988
- # create create boot and efi partitions
- part /boot/efi --fstype=efi --ondisk=sda --size=572
- part /boot --fstype=xfs --ondisk=sda --size=953
- # create volume groups
- volgroup rhel --pesize=4096 pv.01
- volgroup data --pesize=4096 pv.02
- logvol / --vgname=rhel --fstype=xfs --size=19073 --name=root
- logvol swap --vgname=rhel --fstype=swap --size=1907 --name=swap
- # Network information
- network --bootproto=dhcp --device=enp0s31f6 --ipv6=auto --activate --onboot=on
- network --bootproto=dhcp --device=enp2s0 --ipv6=auto --onboot=off
- reboot
- text
- services --enabled=ostree-remount
- ostreesetup --nogpg --osname=rhel --remote=edge --url={{ ostree_repo_url }} --ref={{ blueprint_ref }}
