---
### Defaults
blueprint_name: ""
microshift: false
iso_bucket_name: "rhde-isos"
base_domain: "sandbox2873.opentlc.com"
subdomain: "ostree"

retries: 100
delay: 60

builder_blueprint_name: rfe_installer_blueprint
builder_blueprint_desc: "RHEL For Edge Installer Blueprint"
builder_blueprint_distro: ""
builder_compose_pkgs:
- ansible-core
- vim-enhanced
builder_compose_customizations:
  user:
    name: "{{ admin_user }}"
    password: "{{ admin_password }}"
    groups:
    - wheel
