---
### Defaults
blueprint_name: ""
microshift: false
iso_bucket_name: "rhde-isos"
base_domain: "sandbox2873.opentlc.com"
subdomain: "ostree"

retries: 100
delay: 60

builder_blueprint_name: rfe_installer_blueprint
builder_blueprint_desc: "RHEL For Edge Installer Blueprint"
builder_blueprint_distro: ""
builder_compose_customizations:
  user:
    name: "{{ admin_user }}"
    password: "{{ admin_password }}"
    groups:
    - wheel
builder_kickstart_options:
- lang en_US.UTF-8
- keyboard us
- timezone America/Los_Angeles --utc
- zerombr
- bootloader --location=mbr --boot-drive=sda
- clearpart --all --initlabel
- ignoredisk --only-use=sda,sdb
- part pv.01 --size=20480 --grow --ondisk=sda
- part /boot --fstype=ext4 --ondisk=sda --size=1024
- part /boot/efi --fstype=efi --ondisk=sda --size=600
- volgroup rhel --pesize=4096 pv.01
- logvol / --vgname=rhel --fstype=xfs --size=15360 --name=root
- logvol swap --vgname=rhel --fstype=swap size=4096 --name=swap
- part pv.02 --size=51200 --grow --ondisk=sdb
- volgroup microshift --pesize=4096 pv.02
- logvol /data --vgname=data --fstype= --size= --name= 
- # Network information
- network --bootproto=dhcp --device=eth0 --ipv6=auto --activate --onboot=on
- network --bootproto=dhcp --device=eth1 --ipv6=auto --activate
- reboot
- text
- services --enabled=ostree-remount
- ostreesetup --nogpg --osname=rhel --remote=edge --url={{ ostree_repo_url }} --ref={{ blueprint_ref }}
