---
- name: check input blueprint is passed
  assert:
    that:
    - blueprint_name != ""
    fail_msg: "blueprint must be specified to build image"

- name: check if output image type is passed
  assert:
    that:
    - not output_image_type == ""
    fail_msg: "Output image type is required"

- name: check valid output image type passed
  assert:
    that:
      - output_image_type in image_types
    fail_msg: "Unsupported output image type: {{ output_image_type }}. Allowed values are: {{ image_types }}"