---
# default variables
fdo_keys_dir: "/etc/fdo/keys"

manufacturing:
  name: fdo-manufacturing-server
  image: "registry.redhat.io/rhel9/fdo-manufacturing-server"
  port: 
    host_port: 8080
    container_port: 8080
  volumes:
  - local_path: "/etc/fdo/stores"
    container_path: "/etc/fdo/stores"
  - local_path: "/etc/fdo/keys"
    container_path: "/etc/fdo/keys"
  - local_path: "/etc/fdo/manufacturing-server.conf.d"
    container_path: "/etc/fdo/manufacturing-server.conf.d"

rendezvous:
  name: fdo-rendezvous-server
  image: "registry.redhat.io/rhel9/fdo-rendezvous-server"
  port:
    host_port: 8082
    container_port: 8082
  volumes:
  - local_path: "/etc/fdo/stores"
    container_path: "/etc/fdo/stores"
  - local_path: "/etc/fdo/keys"
    container_path: "/etc/fdo/keys"
  - local_path: "/etc/fdo/rendezvous-server.conf.d"
    container_path: "/etc/fdo/rendezvous-server.conf.d"

owner_onboarding:
  name: fdo-owner-onboarding-server
  image: "registry.redhat.io/rhel9/fdo-owner-onboarding-server"
  port: 
    host_port: 8081
    container_port: 8081
  volumes:
  - local_path: "/etc/fdo/stores"
    container_path: "/etc/fdo/stores"
  - local_path: "/etc/fdo/keys"
    container_path: "/etc/fdo/keys"
  - local_path: "/etc/fdo/owner-onboarding-server.conf.d"
    container_path: "/etc/fdo/owner-onboarding-server.conf.d"

serviceinfo:
  name: fdo-serviceinfo-api-server
  image: "registry.redhat.io/rhel9/fdo-serviceinfo-api-server"
  port:
    host_port: 8083
    container_port: 8083
  files:
  - path: /etc/resolv.conf
    data: |
      # /etc/resolv.conf for edge devices
      # Managed with best practices for edge deployments

      # Primary and secondary DNS servers
      nameserver 1.1.1.1       # Cloudflare DNS
      nameserver 8.8.8.8       # Google Public DNS
      nameserver 9.9.9.9       # Quad9 DNS

      # Optional: Define a domain for unqualified hostnames
      domain edge.local

      # Optional: Search domains for unqualified hostnames
      search edge.local corp.home.local

      # Reduce query timeout for faster failover
      options timeout:2

      # Attempt queries only once per server before failing over
      options attempts:1

      # Rotate through DNS servers for load balancing
      options rotate

      # Enable EDNS0 for better performance and support for larger responses
      options edns0

      # Ignore dynamic updates if resolv.conf is managed manually
      options no-dynamic
  volumes:
  - local_path: "/etc/fdo/stores"
    container_path: "/etc/fdo/stores"  
  - local_path: "/etc/fdo/keys"
    container_path: "/etc/fdo/keys"
  - local_path: "/etc/fdo/serviceinfo-api-server.conf.d"
    container_path: "/etc/fdo/serviceinfo-api-server.conf.d"