---
- name: download openshift pull secret
  rprakashg.demos.download_pullsecret:
    offline_token: "{{ offline_token }}"
  register: download_pullsecret_result

- name: set pull secret fact
  ansible.builtin.set_fact:
    pull_secret: "{{ download_pullsecret_result.pull_secret }}"