---    
- name: obtain access token from offline token  
  ansible.builtin.uri:
    url: "{{ _token_endpoint }}"
    method: POST
    body_format: form-urlencoded
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body:
      grant_type: "{{ _grant_type }}"
      refresh_token: "{{ offline_token }}"
      client_id: "{{ _client_id }}"
  register: token_response

- name: Fail if token retrieval failed
  when: token_response.status != 200
  ansible.builtin.fail:
    msg: "Failed to retrieve access token"

- name: Extract access token from response
  set_fact:
    access_token: "{{ token_response.json.access_token }}"

- name: Download pull secret
  ansible.builtin.uri:
    url: "{{ _download_pull_secret_url }}"
    method: POST
    headers:
      Authorization: "Bearer {{ access_token }}"
  register: pull_secret_response

- name: fail when error download pull secret
  when: pull_secret_response.status != 200
  ansible.builtin.fail:
    msg: "Failed to download pull secret"

- name: set pull secret
  set_fact:
    pull_secret: "{{ pull_secret_response.json }}"