---
- name: obtain access token from offline token
  vars:
    grant_type: "refresh_token"
    client_id: "rhsm-api"
    token_endpoint: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
    download_pull_secret_url: "https://api.openshift.com/api/accounts_mgmt/v1/access_token"    
  ansible.builtin.uri:
    url: "{{ token_endpoint }}"
    method: POST
    body_format: form-urlencoded
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body:
      grant_type: "{{ grant_type }}"
      refresh_token: "{{ rh_offline_token }}"
      client_id: "{{ client_id }}"
  register: token_response

- name: Fail if token retrieval failed
  when: token_response.status != 200
  ansible.builtin.fail:
    msg: "Failed to retrieve access token"

- name: Extract access token from response
  set_fact:
    access_token: "{{ token_response.json.access_token }}"

- name: Download pull secret
  ansible.builtin.uri:
    url: "{{ download_pull_secret_url }}"
    method: POST
    headers:
      Authorization: "Bearer {{ access_token }}"
  register: pull_secret_response

- name: fail when error download pull secret
  when: pull_secret_response.status != 200
  ansible.builtin.fail:
    msg: "Failed to download pull secret"

- name: set pull secret
  set_fact:
    pull_secret: "{{ pull_secret_response.json }}"