---
- name: create infrastructure resources
  ansible.builtin.import_tasks: create_infra.yml
  when: create_infra | default(true)

- name: check if system is registered
  delegate_to: imagebuilder
  ansible.builtin.stat:
    path: /etc/insights-client/.registered
  register: registered

- name: restart rhcd
  delegate_to: imagebuilder
  when: not registered.stat.exists
  ansible.builtin.service:
    name: rhcd
    state: restarted

- name: register system if not already registered
  when: not registered.stat.exists
  delegate_to: imagebuilder
  become: true
  ansible.builtin.import_tasks: register_system.yml

- name: setup imagebuilder
  delegate_to: imagebuilder
  become: true
  ansible.builtin.import_tasks: setup_imagebuilder.yml
