---
- name: create infrastructure resources
  ansible.builtin.import_tasks: create_infra.yml
  when: create_infra | bool
  
- name: download pull secret
  ansible.builtin.import_tasks: download_pullsecret.yml
  when: offline_token != ""
      
- name: check if system is registered
  hosts: imagebuilder
  become: yes
  ansible.builtin.stat:
    path: /etc/insights-client/.registered
  register: registered

- name: register system if not already registered
  when: not registered.stat.exists
  hosts: imagebuilder
  become: true
  ansible.builtin.import_tasks: register_system.yml

- name: setup imagebuilder
  hosts: imagebuilder
  become: true
  ansible.builtin.import_tasks: setup_imagebuilder.yml
