---
- name: include secrets
  include_vars:
    file: "./vars/secrets.yml"
- name: register the system
  shell: |
    subscription-manager register --username={{ rhuser }} --password={{ rhpassword }} --force
    subscription-manager role --set="Red Hat Enterprise Linux Server"
    subscription-manager service-level --set="Self-Support"
    subscription-manager usage --set="Development/Test"
    subscription-manager attach
    subscription-manager config --rhsm.manage_repos=1
    # subscription-manager repos --enable codeready-builder-for-rhel-9-$(arch)-rpms
    