---
- name: install cockpit httpd firewall
  hosts: imagebuilder
  become: true
  ansible.builtin.dnf:
    state: present
    name: "{{ item }}"
  loop:    
  - firewalld
  - httpd
  - cockpit

- name: Configure Cockpit with TLS using RHEL system roles
  hosts: imagebuilder
  become: true
  ansible.builtin.include_role:
    name: rhel-system-roles.cockpit
  vars:
    cockpit_packages: full
    cockpit_enabled: true
    cockpit_started: true
    cockpit_config:
      Log:
        Fatal: "warnings"
    cockpit_port: 443
    cockpit_manage_firewall: true
    cockpit_manage_selinux: true

- name: Configure Firewall for cockpit
  hosts: imagebuilder
  become: true
  ansible.builtin.include_role:
    name: rhel-system-roles.firewall
  vars:
    firewall:
      service: cockpit
      state: enabled
      