---
- name: Setup imagebuilder
  block:
  - name: Install packages
    ansible.builtin.dnf:
      state: latest
      name: "{{ packages }}"
    vars:
      packages:
      - podman
      - rsync
      - osbuild-composer
      - composer-cli
      - cockpit-composer
      - bash-completion
      - firewalld
      - genisoimage
      - httpd
      - syslinux
      - cockpit
      - weldr-client
      - python3
      - lorax
      - pykickstart
      - coreutils
      - glibc-minimal-langpack
      - pykickstart
      - mtools
      - xorriso
      - isomd5sum
      - butane
      - rpmdevtools
      - rpmlint
      - yum-utils
      - createrepo
      - tree
      - python3-pip
      - python3-toml
  - name: enable cockpit/composer/firewalld/podman
    ansible.builtin.systemd:
      state: started
      enabled: true
      name: "{{ item }}"
    loop:
      - osbuild-composer.socket
      - cockpit.socket
      - podman.socket
      - firewalld
      - httpd.service
  - name: configure firewall to allow access to web console
    ansible.posix.firewalld:
      permanent: true
      immediate: true
      service: "{{ item }}"
      state: enabled
    loop:
      - cockpit
      - http
  - name: install aws cli
    ansible.builtin.command:
      cmd: pip3 install awscli boto3 botocore
      
- name: setup imagebuilder with microshift
  when: microshift | default(true)
  block:
  - name: "creating rhocp-{{ microshift_release }}.toml file"
    ansible.builtin.tempfile:
      state: file
      suffix: toml
    register: microshift_source

  - name: creating rhocp-{{ microshift_release }}.toml configuration file
    ansible.builtin.copy:
      dest: "{{ microshift_source.path }}"
      content: |
        id = "rhocp-{{ microshift_release }}"
        name = "Microshift version {{ microshift_release }}"
        type = "yum-baseurl"
        url = "https://cdn.redhat.com/content/dist/layered/rhel9/{{ ansible_architecture }}/rhocp/{{ microshift_release }}/os"
        check_gpg = true
        check_ssl = true
        system = false
        rhsm = true
  
  - name: "creating fastdatapath.toml file"
    ansible.builtin.tempfile:
      state: file
      suffix: toml
    register: fastdatapath_source

  - name: create fast-datapath.toml configuration file
    ansible.builtin.copy:
      dest: "{{ fastdatapath_source.path }}"
      content: |
        id = "fast-datapath"
        name = "Fast Datapath for RHEL 9 System"
        type = "yum-baseurl"
        url = "https://cdn.redhat.com/content/dist/layered/rhel9/{{ ansible_architecture }}/fast-datapath/os"
        check_gpg = true
        check_ssl = true
        system = false
        rhsm = true

  - name: add sources to image builder
    ansible.builtin.command: "sudo composer-cli sources add {{ item }}"
    loop:
      - "{{ microshift_source.path }}"
      - "{{ fastdatapath_source.path }}"

- name: Create a directory for custom rpms
  block:
  - name: check if custom rpms directory is already created
    ansible.builtin.stat:
      path: ~/custom-rpms
    register: customrpm_dir_stat
  - name: Create customrpm dir if it doesnt exist
    when: not customrpm_dir_stat.stat.exists
    ansible.builtin.file:
      path: ~/custom-rpms 
      state: directory
      mode: "0755"

- name: Setup custom rpm repo for greenboot failing package and add to imagebuilder sources
  block:
  - name: create a directory to store the greenboot failing RPM package
    ansible.builtin.file:
      path: ~/custom-rpms/local-greenboot
      state: directory
      mode: "0755"
  - name: Download the green boot failing package 
    ansible.builtin.get_url:
      url: https://kite-webhook-prod.s3.amazonaws.com/greenboot-failing-unit-1.0-1.el8.noarch.rpm
      dest: ~/custom-rpms/local-greenboot
      mode: '0755'
  - name: createrepo
    ansible.builtin.shell: |
      createrepo ~/custom-rpms/local-greenboot
  - name: create a temp toml file
    ansible.builtin.tempfile:
      state: file
      suffix: toml
    register: greenboot_local_source
  - name: add source
    ansible.builtin.copy:
      dest: "{{ greenboot_local_source.path }}"
      content: |
        id = "local-greenboot"
        name = "local-greenboot"
        type = "yum-baseurl"
        url = "file:///root/custom-rpms/local-greenboot"
        check_gpg = false
        check_ssl = false
        system = false
  - name: add source to image builder
    ansible.builtin.shell: |
      sudo composer-cli sources add "{{ greenboot_local_source.path }}"

- name: add pull-secret to image builder
  block:
  - name: include secrets
    include_vars:
      file: "./vars/secrets.yml"
  - name: create /etc/osbuild-worker directory
    ansible.builtin.file:
      path: /etc/osbuild-worker
      state: directory
  - name: create the pull-secret.json file
    ansible.builtin.copy:
      content: "{{ pull_secret }}"
      dest: /etc/osbuild-worker/pull-secret.json
  - name: create osbuild worker toml
    ansible.builtin.copy:
      content: |
        [containers]
        auth_file_path = "/etc/osbuild-worker/pull-secret.json"
      dest: /etc/osbuild-worker/osbuild-worker.toml

- name: Add user to weldr
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: weldr
    append: true
          
- name: reboot imagebuilder
  block:
  - name: rebooting server
    ansible.builtin.reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
  - name: Pinging the imagebuilder
    ansible.builtin.ping:
  - debug:
      msg: "Finished rebooting imagebuilder"
