---
- name: preflight
  delegate_to: imagebuilder
  become: true
  ansible.builtin.import_tasks: preflight.yml

- name: compose
  delegate_to: imagebuilder
  become: true
  when: compose | default(true)
  ansible.builtin.import_tasks: compose.yml

- name: containerize
  delegate_to: imagebuilder
  become: true
  ansible.builtin.import_tasks: containerize.yml

  