---
- name: preflight
  become: true
  when: not blueprint == ""
  ansible.builtin.import_tasks: preflight.yml

- name: compose
  become: true
  when: not blueprint == ""
  ansible.builtin.import_tasks: compose.yml

- name: bootable container build
  become: true
  when: not dockerfile == ""
  ansible.builtin.import_tasks: bootc-build.yml