---
- name: preflight
  become: true
  ansible.builtin.import_tasks: preflight.yml

- name: compose
  become: true
  when: compose | default(true)
  ansible.builtin.import_tasks: compose.yml

- name: containerize
  become: true
  when: containerize | default(true)
  ansible.builtin.import_tasks: containerize.yml

- name: deploy to fargate
  when: deploy_to_fargate | default(true)
  ansible.builtin.import_tasks: deploy_to_fargate.yml  