---
- name: check input blueprint is passed
  assert:
    that:
    - blueprint != ""
    fail_msg: "blueprint must be specified to build image"

- name: create blueprints directory on imagebuilder server if it doesn't exist
  ansible.builtin.file:
    path: "{{ blueprints_dir }}"
    state: directory
    mode: '0755'
    
- name: copy blueprint to imagebuilder
  ansible.builtin.copy:
    src: "{{ blueprint }}"
    dest: "{{ blueprints_dir }}/{{ blueprint | basename }}"

- name: read the contents of input blueprint
  set_fact:
    blueprint_data: "{{ lookup('file', blueprint) | b64encode }}"

- name: get blueprint name
  ansible.builtin.shell: "echo '{{ blueprint_data | b64decode }}' | python -c 'import sys, toml; print(toml.loads(sys.stdin.read())[\"name\"])'"
  register: get_blueprint_name_result

- name: debug blueprint name
  ansible.builtin.debug:
    var: get_blueprint_name_result.stdout

- name: get blueprint version
  ansible.builtin.shell: "echo '{{ blueprint_data | b64decode }}' | python -c 'import sys, toml; print(toml.loads(sys.stdin.read())[\"version\"])'"
  register: get_blueprint_version_result

- name: debug blueprint name
  ansible.builtin.debug:
    var: get_blueprint_version_result.stdout

- name: set blueprint name and version
  set_fact:
    blueprint_name: "{{ get_blueprint_name_result.stdout }}"
    blueprint_version: "{{ get_blueprint_version_result.stdout }}"

- name: set builder blueprint
  set_fact:
    builder_blueprint: "{{ blueprints_dir }}/{{ blueprint | basename }}"

- name: check if blueprint is already added to osbuild composer
  ansible.builtin.shell: composer-cli --json blueprints show "{{ blueprint_name }}" | jq ".[].body.blueprints[].version"
  register: blueprint_show_result
  ignore_errors: yes

- name: debug blueprint show result
  ansible.builtin.debug:
    var: blueprint_show_result

- name: set current version in fact
  set_fact:
    blueprint_current_version: "{{ blueprint_show_result.stdout }}"

- name: push the builder blueprint to imagebuilder if doesnt exist or new version
  when: blueprint_current_version != blueprint_version
  ansible.builtin.shell: composer-cli blueprints push "{{ builder_blueprint }}"
  
- name: check if dev repo is already initialized
  ansible.builtin.stat:
    path: "/home/ostree/{{ blueprint_name }}/repo-dev"
  register: dev_dir_stat

- name: check if prod repo is already initialized
  ansible.builtin.stat:
    path: "/home/ostree/{{ blueprint_name }}/repo-prod"
  register: prod_dir_stat

- name: initialize ostree repos
  when: 
  - not prod_dir_stat.stat.exists
  - not dev_dir_stat.stat.exists
  block:
    - name: create directory
      ansible.builtin.file:
        path: "/home/ostree/{{ blueprint_name }}"
        state: directory
        mode: "0755"

    - name: initialize dev repository
      ansible.builtin.command:
        chdir: "/home/ostree/{{ blueprint_name }}"
        cmd: "ostree --repo=repo-dev init --mode=archive"
      args:
        creates: "/home/ostree/{{ blueprint_name }}/repo-dev"
    
    - name: Initialize prod repository
      ansible.builtin.command:
        chdir: "/home/ostree/{{ blueprint_name }}"
        cmd: "ostree --repo=repo-prod init --mode=archive"
      args:
        creates: "/home/ostree/{{ blueprint_name }}/repo-prod"