---
- name: check input blueprint is passed
  assert:
    that:
    - blueprint != ""
    fail_msg: "blueprint must be specified to build image"

- name: create blueprints directory on imagebuilder server if it doesn't exist
  #ansible.builtin.file:
  #  path: "{{ blueprints_dir }}"
  #  state: directory
  #  mode: '0755'
  #  owner: "{{ ansible_user }}"
  ansible.builtin.tmpfile:

- name: copy blueprint to imagebuilder
  ansible.builtin.copy:
    src: "{{ blueprint }}"
    dest: "{{ blueprints_dir }}/{{ blueprint | basename }}"

- name: read the contents of input blueprint
  set_fact:
    blueprint_data: "{{ lookup('file', blueprint) | b64encode }}"

- name: get blueprint name
  ansible.builtin.shell: "echo '{{ blueprint_data | b64decode }}' | python -c 'import sys, toml; print(toml.loads(sys.stdin.read())[\"name\"])'"
  register: get_blueprint_name_result

- name: get blueprint version
  ansible.builtin.shell: "echo '{{ blueprint_data | b64decode }}' | python -c 'import sys, toml; print(toml.loads(sys.stdin.read())[\"version\"])'"
  register: get_blueprint_version_result

- name: set blueprint name and version
  set_fact:
    blueprint_name: "{{ get_blueprint_name_result.stdout }}"
    blueprint_version: "{{ get_blueprint_version_result.stdout }}"

- name: debug blueprint name
  ansible.builtin.debug:
    msg: "Blueprint Name: {{ blueprint_name }}"

- name: debug blueprint version
  ansible.builtin.debug:
    msg: "Blueprint Version: {{ blueprint_version }}"

- name: set builder blueprint
  set_fact:
    builder_blueprint: "{{ blueprints_dir }}/{{ blueprint | basename }}"

- name: check if blueprint is already added to osbuild composer
  ansible.builtin.shell: composer-cli --json blueprints show "{{ blueprint_name }}" | jq -r ".[].body.blueprints[].version"
  register: blueprint_show_result
  ignore_errors: yes
    
- name: set current version in fact
  when: blueprint_show_result.rc == 0
  set_fact:
    blueprint_current_version: "{{ blueprint_show_result.stdout }}"

- name: debug current blueprint version
  when: blueprint_show_result.rc == 0
  ansible.builtin.debug:
    msg: "Current blueprint version in osbuild composer: {{ blueprint_current_version }}"

- name: push the builder blueprint to imagebuilder if doesnt exist or new version
  when: ( blueprint_show_result.rc == 0 and blueprint_current_version != blueprint_version)
  ansible.builtin.shell: composer-cli blueprints push "{{ builder_blueprint }}"

- name: check if dev repo is already initialized
  ansible.builtin.stat:
    path: "/var/www/html/{{ blueprint_name }}"
  register: blueprint_dir_stat

- name: initialize ostree repos
  when: 
  - not blueprint_dir_stat.stat.exists
  block:
    - name: create directory
      ansible.builtin.file:
        path: "/var/www/html/{{ blueprint_name }}"
        state: directory
        mode: "0755"

    - name: initialize rpm-ostree repository for blueprint
      ansible.builtin.command:
        chdir: "/var/www/html/{{ blueprint_name }}"
        cmd: "ostree --repo=repo init --mode=archive"
      args:
        creates: "/var/www/html/{{ blueprint_name }}/repo"