---
galaxy_info:
  role_name: "install_configure_fdo"
  standalone: false
  company: ""
  description: >
    Install and configure FDO servers
  author: rprakashg
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.12"
  platforms:
  galaxy_tags:
    - edge
    - rhel
    - os
    - fdo
dependencies: []
