---
### Defaults for configuring local environment
cockpit: false
domain: "sandbox1364.opentlc.com"
terraform_dir: ./terraform
cockpit_cert: ./certs/cockpitcert.pem
cockpit_cert_private_key: ./certs/cockpitcert_private_key.pem

microshift: true
microshift_release: 4.16
