---
galaxy_info:
  role_name: "install_haproxy"
  standalone: false
  company: ""
  description: >
    Install HAProxy server
  author: rprakashg
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.12"
  platforms:
  galaxy_tags:
    - edge
    - rhel
    - os
    - fdo
    - HAProxy
dependencies: []
