---
- name: Create directory to store haproxy config
  become: true
  ansible.builtin.file:
    path: /usr/local/etc/haproxy
    state: directory
    mode: 755

- name: Create the HA Proxy config file
  become: true
  ansible.builtin.copy:
    content: |
      {{ cfg }}
    dest: /usr/local/etc/haproxy/haproxy.cfg

- name: make directory to store podman quadlet files
  become: true
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    mode: 755

- name: Create HAProxy container quadlet file
  become: true
  ansible.builtin.template:
    src: "haproxy.container.j2"
    dest: "/etc/containers/systemd/{{ name }}.container"

- name: configure firewall rules
  become: true
  ansible.builtin.firewalld:
    port: "80/tcp"
    state: enabled
    permanent: yes

- name: Configure SELinux
  become: true
  ansible.builtin.shell: |
    semanage port -a -t http_port_t -p tcp 80
  ignore_errors: true

- name: Reload firewall
  become: true
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: perform a systemd daemon reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: enable and start proxy server container
  become: true
  ansible.builtin.systemd:
    name: "{{ name }}"
    state: started
    enabled: yes

- name: check service started successfully
  become: true
  ansible.builtin.systemd:
    name: "{{ name }}"
  register: service_status
  failed_when: false

- name: debug service status
  become: true
  ansible.builtin.debug:
    var: service_status

