- name: Install packages
  ansible.builtin.dnf:
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
    - podman
    - rhc
    - firewalld

- name: make directory to store podman quadlet files
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    mode: 755
