---
- name: create quadlet for rendezvous server container
  ansible.builtin.template:
    src: "server.container.j2"
    dest: /etc/containers/systemd/fdo_rendezvous.container
  vars:
    description: "{{ rendezvous.desc }}"
    image: "{{ rendezvous.image }}"
    name: "{{ rendezvous.name }}"
    host_port: "{{ rendezvous.port.host_port }}"
    container_port: "{{ rendezvous.port.container_port }}"
    host_path: "/etc/fdo/rendezvous-server.conf.d"
    container_path: "/etc/fdo/rendezvous-server.conf.d"
    dest: "/etc/fdo/rendezvous-server.conf.d"

- name: create rendezvous server config file
  ansible.builtin.template:
    src: "rendezvous-server.yml.j2"
    dest: /etc/fdo/rendezvous-server.conf.d/rendezvous-server.yml
    mode: 0644
- name: configure firewall rules
  ansible.builtin.firewalld:
    port: "{{ rendezvous.port.host_port | default('8082') }}/tcp"
    state: enabled
    permanent: yes
- name: Set SELinux
  ansible.builtin.shell: |
    semanage port -a -t http_port_t -p tcp {{ rendezvous.port.host_port | default('8082') }}
  ignore_errors: true
- name: Reload firewall
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

# due to a bug when installing fdo tools fdo server RPM packages gets installed
- name: stop and disable the systemd service for owner onboarding server RPM 
  block:
  - name: stop the service
    ansible.builtin.systemd:
      name: "fdo-rendezvous-server"
      state: stopped
  - name: disable the service
    ansible.builtin.systemd:
      name: "fdo-rendezvous-server"
      enabled: false

- name: perform a systemd daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start and enable the rendezvous server container
  ansible.builtin.systemd:
    name: "{{ rendezvous.name }}"
    state: started
    enabled: yes

- name: check service started successfully
  ansible.builtin.systemd:
    name: "{{ rendezvous.name }}"
  register: service_status
  failed_when: false

- name: debug service status
  ansible.builtin.debug:
    var: service_status
