---
- name: create quadlet for serviceinfo api server container
  ansible.builtin.template:
    src: "server.container.j2"
    dest: "/etc/containers/systemd/fdo_serviceinfo_api_server.container"
  vars:
    description: "{{ serviceinfo.desc }}"
    image: "{{ serviceinfo.image }}"
    name: "{{ serviceinfo.name }}"
    host_port: "{{ serviceinfo.port.host_port }}"
    container_port: "{{ serviceinfo.port.container_port }}"
    host_path: "/etc/fdo/serviceinfo-api-server.conf.d"
    container_path: "/etc/fdo/serviceinfo-api-server.conf.d"
    dest: "/etc/fdo/serviceinfo-api-server.conf.d"

- name: Save files 
  ansible.builtin.copy:
    dest: "{{ item.path }}"
    content: |
      {{ item.data }}
  loop: "{{ serviceinfo.files | list }}"
- name: create serviceinfo api server config file
  ansible.builtin.template:
    src: "serviceinfo-api-server.yml.j2"
    dest: /etc/fdo/serviceinfo-api-server.conf.d/serviceinfo-api-server.yml 
- name: configure firewall rules
  ansible.builtin.firewalld:
    port: "{{ serviceinfo.port.host_port | default('8083') }}/tcp"
    state: enabled
    permanent: yes
- name: configure SELinux rules
  ansible.builtin.shell: |
    semanage port -a -t http_port_t -p tcp {{ serviceinfo.port.host_port | default('8083') }}
  ignore_errors: true
- name: reload firewall
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
- name: enable and start serviceinfo api server container
  ansible.builtin.systemd:
    name: "{{ serviceinfo.name }}"
    state: started
    enabled: yes