---
- name: Create quadlet file for fdo manufacturing server container
  ansible.builtin.template:
    src: "fdo_manufacturing.container.j2"
    dest: /etc/containers/systemd/fdo_manufacturing.container

- name: Create fdo manufacturing server config file
  ansible.builtin.template:
    src: "manufacturing-server.yml.j2"
    dest: /etc/fdo/manufacturing-server.conf.d/manufacturing-server.yml
    mode: 0644

- name: configure firewall rules
  ansible.builtin.firewalld:
    port: "{{ manufacturing.port.host_port | default('8080')}}/tcp"
    state: enabled
    permanent: yes

- name: Configure SELinux
  ansible.builtin.shell: |
    semanage port -a -t http_port_t -p tcp {{ manufacturing.port.host_port | default('8080')}}
  ignore_errors: true

- name: Reload firewall
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: enable and start manufacturing server container
  ansible.builtin.systemd:
    name: "fdo_manufacturing.container"
    state: started
    enabled: yes
