---
- name: Create quadlet file for fdo manufacturing server container
  ansible.builtin.template:
    src: "server.container.j2"
    dest: /etc/containers/systemd/fdo_manufacturing.container
  vars:
    description: "{{ manufacturing.desc }}"
    image: "{{ manufacturing.image }}"
    name: "{{ manufacturing.name }}"
    host_port: "{{ manufacturing.port.host_port }}"
    container_port: "{{ manufacturing.port.container_port }}"
    host_path: "/etc/fdo/manufacturing-server.conf.d"
    container_path: "/etc/fdo/manufacturing-server.conf.d"
    dest: "/etc/fdo/manufacturing-server.conf.d"

- name: Create fdo manufacturing server config file
  ansible.builtin.template:
    src: "manufacturing-server.yml.j2"
    dest: /etc/fdo/manufacturing-server.conf.d/manufacturing-server.yml
    mode: 0644

- name: configure firewall rules
  ansible.builtin.firewalld:
    port: "{{ manufacturing.port.host_port | default('8080')}}/tcp"
    state: enabled
    permanent: yes

- name: Configure SELinux
  ansible.builtin.shell: |
    semanage port -a -t http_port_t -p tcp {{ manufacturing.port.host_port | default('8080')}}
  ignore_errors: true

- name: Reload firewall
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

# due to a bug when installing fdo tools fdo server RPM packages gets installed
- name: stop and disable the systemd service for manufacturing server RPM 
  block:
  - name: stop the service
    ansible.builtin.systemd:
      name: "fdo-manufacturing-server"
      state: stopped
  - name: disable the service
    ansible.builtin.systemd:
      name: "fdo-manufacturing-server"
      enabled: false

- name: perform a systemd daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: enable and start manufacturing server container
  ansible.builtin.systemd:
    name: "{{ manufacturing.name }}"
    state: started
    enabled: true

- name: check service started successfully
  ansible.builtin.systemd:
    name: "{{ manufacturing.name }}"
  register: service_status
  failed_when: false

- name: debug service status
  ansible.builtin.debug:
    var: service_status
