---
- name: check if system is registered
  ansible.builtin.stat:
    path: /etc/insights-client/.registered
  register: registered
- name: register system if not already registered
  when: not registered.stat.exists
  become: true
  ansible.builtin.import_tasks: register_system.yml
- name: preflight
  become: true
  ansible.builtin.import_tasks: preflight.yml
- name: install fdo manufacturing server
  become: true
  ansible.builtin.import_tasks: fdo_manufacturing.yml
- name: install fdo rendezvous server
  become: true
  ansible.builtin.import_tasks: fdo_rendezvous.yml
- name: install serviceinfo api server
  become: true
  ansible.builtin.import_tasks: fdo_serviceinfo_api.yml
- name: install owner onboarding server
  become: true
  ansible.builtin.import_tasks: fdo_owner_onboarding.yml
- name: install health monitoring ping proxy forwarder
  become: true
  ansible.builtin.import_tasks: ping_proxy.yml