---
- name: preflight
  become: true
  ansible.builtin.import_tasks: preflight.yml
- name: initialize_db.yml
  become: true
  ansible.builtin.import_tasks: initialize_db.yml
- name: install fdo manufacturing server
  become: true
  ansible.builtin.import_tasks: fdo_manufacturing.yml
- name: install fdo rendezvous server
  become: true
  ansible.builtin.import_tasks: fdo_rendezvous.yml
- name: install serviceinfo api server
  become: true
  ansible.builtin.import_tasks: fdo_serviceinfo_api.yml
- name: install owner onboarding server
  become: true
  ansible.builtin.import_tasks: fdo_owner_onboarding.yml