---
- name: Create directory to store haproxy config
  ansible.builtin.file:
    path: /usr/local/etc/haproxy
    state: directory
    mode: 755

- name: Create the HA Proxy config file
  ansible.builtin.template:
    src: "haproxy.cfg.j2"
    dest: /usr/local/etc/haproxy/haproxy.cfg

- name: Create HAProxy container quadlet file
  ansible.builtin.template:
    src: "haproxy-app.container.j2"
    dest: "/etc/containers/systemd/haproxy-app.container"

- name: configure firewall rules
  ansible.builtin.firewalld:
    port: "80/tcp"
    state: enabled
    permanent: yes

- name: Configure SELinux
  ansible.builtin.shell: |
    semanage port -a -t http_port_t -p tcp 80
  ignore_errors: true

- name: Reload firewall
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: enable and start manufacturing server container
  ansible.builtin.systemd:
    name: "haproxy-app"
    state: started
    enabled: yes
