---
- name: make directory to store podman quadlet files
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    mode: 755
- name: make a drop in directory for manufacturing server config
  ansible.builtin.file:
    path: /etc/fdo/{{ item }}-server.conf.d
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
  - manufacturing
  - rendezvous
  - serviceinfo-api
  - owner-onboarding

- name: create quadlet volume files for container storage
  block:
  - name: Create quadlet volume for stores
    ansible.builtin.template:
      src: "server.volume.j2"
      dest: "/etc/containers/systemd/fdo-stores.volume"
    vars:
      volume_name: "fdo-stores"
      volume_description: "FDO Stores volume"
      volume_label: "app=fdo-server"
      volume_src: "/etc/fdo/stores"
      volume_dst: "/etc/fdo/stores"
  - name: Create quadlet volume for stores
    ansible.builtin.template:
      src: "server.volume.j2"
      dest: "/etc/containers/systemd/fdo-keys.volume"
    vars:
      volume_name: "fdo-keys"
      volume_description: "FDO Keys volume"
      volume_label: "app=fdo-server"
      volume_src: "/etc/fdo/keys"
      volume_dst: "/etc/fdo/keys"
  - name: Create volume for config directories
    ansible.builtin.template:
      src: "server.volume.j2"
      dest: "/etc/containers/systemd/{{ item }}-server.conf.d.volume"
    vars:
      volume_name: "{{ item }}"
      volume_description: "{{ item }} volume"
      volume_label: "app=fdo-server"
      volume_src: "/etc/fdo/{{ item }}-server.conf.d"
      volume_dst: "/etc/fdo/{{ item }}-server.conf.d"
    loop:
    - manufacturing
    - rendezvous
    - serviceinfo-api
    - owner-onboarding

- name: Install FDO tools
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - fdo-admin-cli
    - fdo-owner-cli
    - firewalld
- name: generate keys and certs
  ansible.builtin.command: |
    fdo-admin-tool generate-key-and-cert --destination-dir {{ fdo_keys_dir }} {{ item }}
  with_items:
  - diun
  - manufacturer
  - device-ca
  - owner
