blueprint_distro_lower: "{{ 'rhel' if ansible_distribution == 'RedHat' else ansible_distribution | lower }}"
blueprint_ref: "{{ blueprint_distro_lower }}/{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/x86_64/{{ 'iot' if ansible_distribution == 'Fedora' else 'edge' }}"

_builder_kickstart_pre:
- "{{ lookup('ansible.builtin.template', '../templates/kickstart_pre.j2')}}"
builder_kickstart_pre: "{{ _builder_kickstart_pre + additional_kickstart_pre if additional_kickstart_pre is defined else (_builder_kickstart_pre if _builder_kickstart_pre is defined else None) | default(None) }}"

builder_kickstart_options:
- lang en_US.UTF-8
- keyboard us
- timezone America/Los_Angeles --utc
- zerombr
- clearpart --all --initlabel
- # Create physical volumes
- part pv.01 --fstype=lvmpv --ondisk=sda --grow --size=20988
- part pv.02 --fstype=lvmpv --ondisk=sdb --grow --size=20988
- # create volume group for disk 1
- part /boot/efi --fstype=efi --ondisk=sda --size=572
- part /boot --fstype=xfs --ondisk=sda --size=953
- # create volume groups
- volgroup rhel --pesize=4096 pv.01
- volgroup data --pesize=4096 pv.02
- logvol / --vgname=rhel --fstype=xfs --size=19073 --name=root
- logvol swap --vgname=rhel --fstype=swap --size=1907 --name=swap
- # Network information
- network --bootproto=dhcp --device=enp0s31f6 --ipv6=auto --activate --onboot=on
- network --bootproto=dhcp --device=enp2s0 --ipv6=auto --onboot=off
- reboot
- text
- services --enabled=ostree-remount
- ostreesetup --nogpg --osname=rhel --remote=edge --url={{ ostree_repo_url }} --ref={{ blueprint_ref }}

_builder_kickstart_post:
- "{{ lookup('ansible.builtin.template', '../templates/kickstart_post.j2')}}"
builder_kickstart_post: "{{ _builder_kickstart_post + additional_kickstart_post if additional_kickstart_post is defined else (_builder_kickstart_post if _builder_kickstart_post is defined else None) | default(None) }}"

