---
- name: start
  ansible.builtin.debug:
    msg: "Creating ami images for bootc image {{ image_name }}"
    
- name: create ami
  ansible.builtin.shell: |
    podman run \
      --rm \
      -it \
      --privileged \
      --pull=newer \
      registry.redhat.io/rhel9/bootc-image-builder:latest \
      --type ami \
      --aws-ami-name "{{ image_name }}-x86" \
      --aws-bucket "{{ ami_bucket_name }}" \
      --aws-region "{{ aws_region }}" \
      {{ registry }}/{{ registry_user }}/{{ image_name }}:{{ tag }}

