---
- name: check valid output image type passed
  assert:
    that:
      - output_image_type in image_types
    fail_msg: "Invalid choice: {{ output_image_type }}. Allowed values are: {{ image_types }}"
  
- name: build iso
  become: true
  when: output_image_type == "iso"
  ansible.builtin.import_tasks: create_iso_installer.yml
  
- name: build ami
  become: true
  when: output_image_type == "ami"
  ansible.builtin.import_tasks: create_ami.yml
