---
- name: check valid output image type passed
  assert:
    that:
      - output_image_type in image_types
    fail_msg: "Invalid choice: {{ output_image_type }}. Allowed values are: {{ image_types }}"

- name: build iso
  ansible.builtin.import_tasks: create_iso_installer.yml
  when: output_image_type == "iso"

- name: build ami
  when: output_image_type == "ami"
  ansible.builtin.import_tasks: create_ami.yml
