---
- name: login to registry.redhat.io
  ansible.builtin.shell: |
    podman login --username="{{ rhuser }}" --password="{{ rhpassword }}" registry.redhat.io
  register: login_result

- name: Debug login result
  ansible.builtin.debug:
    var: login_result

- name: Pull bootc image builder
  ansible.builtin.shell: |
    podman pull registry.redhat.io/rhel9/bootc-image-builder

- name: Login to registry
  containers.podman.podman_login:
    username: "{{ rhuser }}"
    password: "{{ rhpassword }}"
    registry: "{{ registry }}"
  result: registry_login_result

- name: debug login
  ansible.builtin.debug:
    var: registry_login_result

- name: Pull image
  ansible.builtin.shell: |
    podman pull {{ registry }}/{{ registry_user }}/{{ image_name }}:{{ tag }}