---
- name: Create edge commit
  hosts: imagebuilder
  tasks:
  - name: load secrets from ansible vault
    include_vars:
      file: "./vars/secrets.yml"
  - name: build edge commit
    ansible.builtin.include_role:
      name: rprakashg.demos.build_edge_commit
    vars:
      blueprint: "../blueprints/rhde.toml"