---
- name: Create ISO image
  hosts: imagebuilder
  tasks:
  - name: load secrets from ansible vault
    include_vars:
      file: "./vars/secrets.yml"
  - name: create iso
    ansible.builtin.include_role:
      name: rprakashg.demos.create_iso
    vars:
      blueprint_name: "rhde"
      iso_bucket_name: "rhde-isos"
      base_domain: "sandbox2873.opentlc.com"
      subdomain: "ostree"
