---
- name: Create edge commit
  hosts: imagebuilder
  tasks:
  - name: load secrets from ansible vault
    include_vars:
      file: "./vars/secrets.yml"
  - name: build edge commit
    ansible.builtin.include_role:
      name: rprakashg.demos.build_edge_commit
    vars:
      builder_blueprint_name: rhde
      builder_blueprint_description: "Base Red Hat Device Edge 9.4 blueprint"
      builder_blueprint_distro: "rhel-9"
      builder_compose_pkgs:
      - cockpit
      - cockpit-ostree
      - cockpit-podman
      - greenboot
      - greenboot-grub2
      - greenboot-default-health-checks
      - microshift
      - microshift-greenboot
      - microshift-networking
      - microshift-release-info
      - microshift-selinux
      - lvm2
      builder_compose_customizations:
        services:
          enabled: ["microshift", "cockpit.socket", "podman.socket", "podman.service", "firewalld", "rpm-ostreed-automatic.timer", "podman-auto-update.timer", "applyupdate.timer"]
        firewall:
          services:
            enabled: ["http", "https", "ssh", "cockpit", "kube-apiserver", "kube-nodeport-services", "dhcpv6-client"]
            disabled: ["telnet"]
          ports: ["8080:tcp", "9090:tcp", "8081:tcp", "8089:tcp", "8096:tcp", "8443:tcp", "8480:tcp", "9091:tcp", "9099:tcp"]
        directories:
        - path: "/etc/systemd/system/podman-auto-update.timer.d"
        - path: "/etc/greenboot/check/required.d"
        files:
        - path: "/etc/systemd/system/podman-auto-update.timer.d/splay.conf"
          data: |
            [Timer]
            RandomizedDelaySec=7200
        - path: "/etc/rpm-ostreed.conf"
          data: |
            [Daemon]
            AutomaticUpdatePolicy=stage
        - path: "/etc/systemd/system/applyupdate.service"
          data: |
            [Unit]
            Description=Apply Update Check

            [Service]
            Type=oneshot
            ExecStart=/bin/sh -c 'if [[ $(rpm-ostree status -v | grep "Staged: yes") ]]; then systemctl --message="Applying OTA update" reboot; else logger "Running latest available update"; fi
        - path: "/etc/systemd/system/applyupdate.timer"
          data: |
            [Unit]
            Description=Daily Update Reboot Check

            [Timer]
            OnCalendar=Sun *-*-* 00:00:00

            [Install]
            WantedBy=multi-user.target
        - path: "/etc/systemd/journald.conf.d/microshift.conf"
          data: |
            [Journal]
            Storage=persistent
            SystemMaxUse=1G
            RuntimeMaxUse=1G
        - path: "/etc/microshift/lvmd.yaml"
          data: |
            # Unix domain socket endpoint of gRPC
            socket-name: /run/lvmd/lvmd.socket
            device-classes:
              # The name of a device-class
              - name: default
                # The group where this device-class creates the logical volumes
                volume-group: rhel
                # Storage capacity in GiB to be spared
                spare-gb: 100
                # A flag to indicate that this device-class is used by default
                default: true
        - path: "/etc/microshift/manifests.d/argocd/kustomization.yaml"
          data: |
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            namespace: argocd
            resources:
            - namespace.yaml
            - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        - path: "/etc/microshift/manifests.d/argocd/namespace.yaml"
          data: |
            apiVersion: v1
            kind: Namespace
            metadata:
              name: argocd
              labels:
                name: argocd
        - path: "/etc/microshift/manifests.d/argocd/route.yaml"
          data: |
            