---
- name: Install OpenShift Cluster on AWS
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Install cluster
    rprakashg.demos.install_openshift_on_aws:
      cluster_name: demo
      region: us-west-2
      base_domain: sandbox2519.opentlc.com
      worker_instance_type: m5.4xlarge
      worker_replicas: 1
      master_instance_type: c5.4xlarge
      master_replicas: 1
    register: install_result
  - name: Debug result
    ansible.builtin.debug:
      var: install_result