---
- name: Installl FDO playbook
  hosts: fdo
  tasks:
  - name: load secrets from ansible vault
    include_vars:
      file: "./vars/secrets.yml"
  - name: install FDO
    ansible.builtin.include_role:
      name: rprakashg.demos.install_fdo