---
- name: Install and Configure FDO example playbook
  hosts: localhost
  tasks:
  - name: load secrets from ansible vault
    include_vars:
      file: "./vars/secrets.yml"
  - name: install FDO
    ansible.builtin.include_role:
      name: rprakashg.demos.install_configure_fdo