---
- name: Install OpenShift Cluster on AWS
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Install
    ansible.builtin.include_role:
      name: rprakashg.demos.install_openshift_on_aws
    vars:
      cluster_name: demo
      region: us-west-2
      base_domain: sandbox2519.opentlc.com
      worker_instance_type: m5.4xlarge
      worker_replicas: 1
      master_instance_type: c5.4xlarge
      master_replicas: 1
      